### ISSUE TITLE
scan_quick_policy creates template'd scans, not policie'd

### ISSUE THREAD

**Issue by isbear** [kost/nessus_rest-ruby#1]
Hello.

#scan_quick_policy(policyname, name, targets) as far, as I understand, should create a scan with given policy. But in fact it creates scan with template, parent to policy, not with the policy itself. Here's example — I created two policies from one template, and got this from #list_policies():

```ruby
{"policies"=>
  [{"no_target"=>"false",
    "template_uuid"=>"ad......66",
    "description"=>"\n",
    "name"=>"test1",
    "owner"=>"isbear",
    "visibility"=>"shared",
    "shared"=>1,
    "user_permissions"=>32,
    "last_modification_date"=>1495717055,
    "creation_date"=>1489694734,
    "owner_id"=>2,
    "id"=>10},
   {"no_target"=>"false",
    "template_uuid"=>"ad......66",
    "description"=>"\n",
    "name"=>"test",
    "owner"=>"isbear",
    "visibility"=>"shared",
    "shared"=>1,
    "user_permissions"=>128,
    "last_modification_date"=>1497046024,
    "creation_date"=>1497046024,
    "owner_id"=>2,
    "id"=>79}]}
```

As you can see, they share the same template_uuid. What they do not share is their policy id, and thus it should be specified in options hash to scan_create to distinguish between policy and template. I.e. currently you're in the end are calling this:

```ruby
scan_create("ad......66", {name: "test", text_targets: "list of ips from arguments"}) # plus merged @quick_defaults
```

while it should be:

```ruby
scan_create("ad......66", {name: "test", policy_id: 79, text_targets: "list of ips from argemnts"}) # plus merged @quick_defaults
```

**Comment by kost** [comment]
Thanks on report. Will test out the patch and get back to you.
